// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/cqrs/base"
	core "github.com/bborbe/notification"
	"github.com/bborbe/notification-controller/pkg"
)

type NotificationSender struct {
	SendDeleteStub        func(context.Context, base.Identifier) error
	sendDeleteMutex       sync.RWMutex
	sendDeleteArgsForCall []struct {
		arg1 context.Context
		arg2 base.Identifier
	}
	sendDeleteReturns struct {
		result1 error
	}
	sendDeleteReturnsOnCall map[int]struct {
		result1 error
	}
	SendUpdateStub        func(context.Context, core.Notification) error
	sendUpdateMutex       sync.RWMutex
	sendUpdateArgsForCall []struct {
		arg1 context.Context
		arg2 core.Notification
	}
	sendUpdateReturns struct {
		result1 error
	}
	sendUpdateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *NotificationSender) SendDelete(arg1 context.Context, arg2 base.Identifier) error {
	fake.sendDeleteMutex.Lock()
	ret, specificReturn := fake.sendDeleteReturnsOnCall[len(fake.sendDeleteArgsForCall)]
	fake.sendDeleteArgsForCall = append(fake.sendDeleteArgsForCall, struct {
		arg1 context.Context
		arg2 base.Identifier
	}{arg1, arg2})
	stub := fake.SendDeleteStub
	fakeReturns := fake.sendDeleteReturns
	fake.recordInvocation("SendDelete", []interface{}{arg1, arg2})
	fake.sendDeleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *NotificationSender) SendDeleteCallCount() int {
	fake.sendDeleteMutex.RLock()
	defer fake.sendDeleteMutex.RUnlock()
	return len(fake.sendDeleteArgsForCall)
}

func (fake *NotificationSender) SendDeleteCalls(stub func(context.Context, base.Identifier) error) {
	fake.sendDeleteMutex.Lock()
	defer fake.sendDeleteMutex.Unlock()
	fake.SendDeleteStub = stub
}

func (fake *NotificationSender) SendDeleteArgsForCall(i int) (context.Context, base.Identifier) {
	fake.sendDeleteMutex.RLock()
	defer fake.sendDeleteMutex.RUnlock()
	argsForCall := fake.sendDeleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *NotificationSender) SendDeleteReturns(result1 error) {
	fake.sendDeleteMutex.Lock()
	defer fake.sendDeleteMutex.Unlock()
	fake.SendDeleteStub = nil
	fake.sendDeleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *NotificationSender) SendDeleteReturnsOnCall(i int, result1 error) {
	fake.sendDeleteMutex.Lock()
	defer fake.sendDeleteMutex.Unlock()
	fake.SendDeleteStub = nil
	if fake.sendDeleteReturnsOnCall == nil {
		fake.sendDeleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.sendDeleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *NotificationSender) SendUpdate(arg1 context.Context, arg2 core.Notification) error {
	fake.sendUpdateMutex.Lock()
	ret, specificReturn := fake.sendUpdateReturnsOnCall[len(fake.sendUpdateArgsForCall)]
	fake.sendUpdateArgsForCall = append(fake.sendUpdateArgsForCall, struct {
		arg1 context.Context
		arg2 core.Notification
	}{arg1, arg2})
	stub := fake.SendUpdateStub
	fakeReturns := fake.sendUpdateReturns
	fake.recordInvocation("SendUpdate", []interface{}{arg1, arg2})
	fake.sendUpdateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *NotificationSender) SendUpdateCallCount() int {
	fake.sendUpdateMutex.RLock()
	defer fake.sendUpdateMutex.RUnlock()
	return len(fake.sendUpdateArgsForCall)
}

func (fake *NotificationSender) SendUpdateCalls(stub func(context.Context, core.Notification) error) {
	fake.sendUpdateMutex.Lock()
	defer fake.sendUpdateMutex.Unlock()
	fake.SendUpdateStub = stub
}

func (fake *NotificationSender) SendUpdateArgsForCall(i int) (context.Context, core.Notification) {
	fake.sendUpdateMutex.RLock()
	defer fake.sendUpdateMutex.RUnlock()
	argsForCall := fake.sendUpdateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *NotificationSender) SendUpdateReturns(result1 error) {
	fake.sendUpdateMutex.Lock()
	defer fake.sendUpdateMutex.Unlock()
	fake.SendUpdateStub = nil
	fake.sendUpdateReturns = struct {
		result1 error
	}{result1}
}

func (fake *NotificationSender) SendUpdateReturnsOnCall(i int, result1 error) {
	fake.sendUpdateMutex.Lock()
	defer fake.sendUpdateMutex.Unlock()
	fake.SendUpdateStub = nil
	if fake.sendUpdateReturnsOnCall == nil {
		fake.sendUpdateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.sendUpdateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *NotificationSender) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *NotificationSender) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.NotificationSender = new(NotificationSender)
