// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/cqrs/base"
	"github.com/bborbe/kv"
	core "github.com/bborbe/notification"
	"github.com/bborbe/notification-controller/pkg"
)

type TelegramThrottle struct {
	DeleteNotificationStub        func(context.Context, kv.Tx, base.Identifier) error
	deleteNotificationMutex       sync.RWMutex
	deleteNotificationArgsForCall []struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 base.Identifier
	}
	deleteNotificationReturns struct {
		result1 error
	}
	deleteNotificationReturnsOnCall map[int]struct {
		result1 error
	}
	FlushStub        func(context.Context) error
	flushMutex       sync.RWMutex
	flushArgsForCall []struct {
		arg1 context.Context
	}
	flushReturns struct {
		result1 error
	}
	flushReturnsOnCall map[int]struct {
		result1 error
	}
	RunStub        func(context.Context) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 context.Context
	}
	runReturns struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateNotificationStub        func(context.Context, kv.Tx, core.Notification) error
	updateNotificationMutex       sync.RWMutex
	updateNotificationArgsForCall []struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 core.Notification
	}
	updateNotificationReturns struct {
		result1 error
	}
	updateNotificationReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TelegramThrottle) DeleteNotification(arg1 context.Context, arg2 kv.Tx, arg3 base.Identifier) error {
	fake.deleteNotificationMutex.Lock()
	ret, specificReturn := fake.deleteNotificationReturnsOnCall[len(fake.deleteNotificationArgsForCall)]
	fake.deleteNotificationArgsForCall = append(fake.deleteNotificationArgsForCall, struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 base.Identifier
	}{arg1, arg2, arg3})
	stub := fake.DeleteNotificationStub
	fakeReturns := fake.deleteNotificationReturns
	fake.recordInvocation("DeleteNotification", []interface{}{arg1, arg2, arg3})
	fake.deleteNotificationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *TelegramThrottle) DeleteNotificationCallCount() int {
	fake.deleteNotificationMutex.RLock()
	defer fake.deleteNotificationMutex.RUnlock()
	return len(fake.deleteNotificationArgsForCall)
}

func (fake *TelegramThrottle) DeleteNotificationCalls(stub func(context.Context, kv.Tx, base.Identifier) error) {
	fake.deleteNotificationMutex.Lock()
	defer fake.deleteNotificationMutex.Unlock()
	fake.DeleteNotificationStub = stub
}

func (fake *TelegramThrottle) DeleteNotificationArgsForCall(i int) (context.Context, kv.Tx, base.Identifier) {
	fake.deleteNotificationMutex.RLock()
	defer fake.deleteNotificationMutex.RUnlock()
	argsForCall := fake.deleteNotificationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *TelegramThrottle) DeleteNotificationReturns(result1 error) {
	fake.deleteNotificationMutex.Lock()
	defer fake.deleteNotificationMutex.Unlock()
	fake.DeleteNotificationStub = nil
	fake.deleteNotificationReturns = struct {
		result1 error
	}{result1}
}

func (fake *TelegramThrottle) DeleteNotificationReturnsOnCall(i int, result1 error) {
	fake.deleteNotificationMutex.Lock()
	defer fake.deleteNotificationMutex.Unlock()
	fake.DeleteNotificationStub = nil
	if fake.deleteNotificationReturnsOnCall == nil {
		fake.deleteNotificationReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteNotificationReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *TelegramThrottle) Flush(arg1 context.Context) error {
	fake.flushMutex.Lock()
	ret, specificReturn := fake.flushReturnsOnCall[len(fake.flushArgsForCall)]
	fake.flushArgsForCall = append(fake.flushArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.FlushStub
	fakeReturns := fake.flushReturns
	fake.recordInvocation("Flush", []interface{}{arg1})
	fake.flushMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *TelegramThrottle) FlushCallCount() int {
	fake.flushMutex.RLock()
	defer fake.flushMutex.RUnlock()
	return len(fake.flushArgsForCall)
}

func (fake *TelegramThrottle) FlushCalls(stub func(context.Context) error) {
	fake.flushMutex.Lock()
	defer fake.flushMutex.Unlock()
	fake.FlushStub = stub
}

func (fake *TelegramThrottle) FlushArgsForCall(i int) context.Context {
	fake.flushMutex.RLock()
	defer fake.flushMutex.RUnlock()
	argsForCall := fake.flushArgsForCall[i]
	return argsForCall.arg1
}

func (fake *TelegramThrottle) FlushReturns(result1 error) {
	fake.flushMutex.Lock()
	defer fake.flushMutex.Unlock()
	fake.FlushStub = nil
	fake.flushReturns = struct {
		result1 error
	}{result1}
}

func (fake *TelegramThrottle) FlushReturnsOnCall(i int, result1 error) {
	fake.flushMutex.Lock()
	defer fake.flushMutex.Unlock()
	fake.FlushStub = nil
	if fake.flushReturnsOnCall == nil {
		fake.flushReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.flushReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *TelegramThrottle) Run(arg1 context.Context) error {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *TelegramThrottle) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *TelegramThrottle) RunCalls(stub func(context.Context) error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *TelegramThrottle) RunArgsForCall(i int) context.Context {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1
}

func (fake *TelegramThrottle) RunReturns(result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *TelegramThrottle) RunReturnsOnCall(i int, result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *TelegramThrottle) UpdateNotification(arg1 context.Context, arg2 kv.Tx, arg3 core.Notification) error {
	fake.updateNotificationMutex.Lock()
	ret, specificReturn := fake.updateNotificationReturnsOnCall[len(fake.updateNotificationArgsForCall)]
	fake.updateNotificationArgsForCall = append(fake.updateNotificationArgsForCall, struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 core.Notification
	}{arg1, arg2, arg3})
	stub := fake.UpdateNotificationStub
	fakeReturns := fake.updateNotificationReturns
	fake.recordInvocation("UpdateNotification", []interface{}{arg1, arg2, arg3})
	fake.updateNotificationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *TelegramThrottle) UpdateNotificationCallCount() int {
	fake.updateNotificationMutex.RLock()
	defer fake.updateNotificationMutex.RUnlock()
	return len(fake.updateNotificationArgsForCall)
}

func (fake *TelegramThrottle) UpdateNotificationCalls(stub func(context.Context, kv.Tx, core.Notification) error) {
	fake.updateNotificationMutex.Lock()
	defer fake.updateNotificationMutex.Unlock()
	fake.UpdateNotificationStub = stub
}

func (fake *TelegramThrottle) UpdateNotificationArgsForCall(i int) (context.Context, kv.Tx, core.Notification) {
	fake.updateNotificationMutex.RLock()
	defer fake.updateNotificationMutex.RUnlock()
	argsForCall := fake.updateNotificationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *TelegramThrottle) UpdateNotificationReturns(result1 error) {
	fake.updateNotificationMutex.Lock()
	defer fake.updateNotificationMutex.Unlock()
	fake.UpdateNotificationStub = nil
	fake.updateNotificationReturns = struct {
		result1 error
	}{result1}
}

func (fake *TelegramThrottle) UpdateNotificationReturnsOnCall(i int, result1 error) {
	fake.updateNotificationMutex.Lock()
	defer fake.updateNotificationMutex.Unlock()
	fake.UpdateNotificationStub = nil
	if fake.updateNotificationReturnsOnCall == nil {
		fake.updateNotificationReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateNotificationReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *TelegramThrottle) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TelegramThrottle) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.TelegramThrottle = new(TelegramThrottle)
